version: "2.3"

services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 80
      # - 3000:3000
    volumes:
      - .:/var/www/html:delegated
    networks:
      - db-network
    mem_limit: 1G

networks:
  db-network:
    name: db-network
    external: true
