version: "2.3"

services:
  mysql:
    image: mysql:5.7
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION" --character-set-server=utf8 --collation-server=utf8_general_ci
    mem_limit: 1G

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - mysql-network
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    links:
      - mysql
    mem_limit: 1G

volumes:
  mysql_data:

networks:
  mysql-network:
    name: mysql-network