version: "2.3"

services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - ${PORT_80}:80
      - ${PORT_8000}:8000
      - ${PORT_3000}:3000
    volumes:
      - .:/var/www/html:delegated
    links:
      - mysql
    mem_limit: 1G

  mysql:
    image: mysql:5.7
    ports:
      - ${PORT_3306}:3306
    volumes:
      - lampp_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION" --character-set-server=utf8 --collation-server=utf8_general_ci
    mem_limit: 1G

volumes:
  lampp_mysql_data:
